sudo: required
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements_development.txt
script:
  - py.test . -v --cov-report term-missing
after_success:
  - coveralls
