sudo: required
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements_development.txt
script:
  - py.test . --pep8 coveralls -v --cov coveralls --cov-report term-missing --cov-report term-missing
after_success:
  - coveralls
