sudo: required
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements_development.txt
script:
  - coverage run --source=amphipathic -m pytest
after_success:
  - coveralls
